# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b480cd450c44ff1f0cd8d402894ebd3092bf505073f329c3659a1051f0c3eac2e25c21893c91b2f402b0a2a7bb12ddcd3c94075900937f621ff8e4e179d0147

test:
  secret_key_base: 607e3e7fc125cf2592e315e2033315b1df37f599a9d5dfebcfe254d4714415fe983bbabab73e1334e70b672b0bb64936b8576e548c0d27e6c8a1adbb21c4afe2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
